### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by jbarber2016** [leovo2708/ng2-dropdown-treeview#1]
I really love this component.  I think the only thing is when you filter the treeview, you cant uncheck those unfiltered items.  Not sure what is the best way approach it.  But I feel it's quirky if you start out with all checked items, then filter and only really want those filtered items checked.  Maybe I'm thinking about it wrong but at least could have a conversation.

**Comment by leovo2708** [comment]
Hi, thank for your comment.
I am trying to understand your problem, is it that you want to check hidden items by filtering when click on checkbox 'All'? If it is true, why you don't remove filtering before doing this. 
Maybe I don't understand right your problem, could you please give more information?
I'm looking forward to hearing from you.

**Comment by jbarber2016** [comment]
What I mean is the following:  The initial state is everything is checked.  When you filter, even those that are filtered out are still checked.  Which seems illogical to me.  So, should they uncheck everything then filter?  The other choice would be filter, click the select to to deselect everything and pick-and-choose the filtered items.

**Comment by leovo2708** [comment]
Yes, I understand what you mean. The purpose of filtering is to display only matched items, and it shouldn't change state of unmatched items. You should follow the other choice as you suggested or you can fork this repository and make changes if you want.

Finally, this is not a bug, it's a new behavior. Thanks.

**Comment by leovo2708** [comment]
After reviewing your idea, I think it's very difficult to handle in some cases. Example: I want to select 9 items of 10 items in tree, I only need uncheck the remaining item by filtering. Or I want to select 1 item of 10 items in tree, I only need uncheck All and then check the item I want by filtering. So, you will understand that filtering in this case is searching to display only matched items, and it shouldn't change state of unmatched items. I think it's very easy to use than your idea.
So I will not make any changes to follow you idea. You can fork this repository to make changes if you want. Thanks.
