### ISSUE TITLE
Set selected item in multi select dropdown

### ISSUE THREAD

**Issue by sachinkasana** [leovo2708/ng2-dropdown-treeview#10]
Hi,
How can I set the selected items in leo-dropdown-treeview?
Because i have 2 list one is complete list and second is selected items list

Thanks

**Comment by leovo2708** [comment]
Please read example 3: https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/

**Comment by leovo2708** [comment]
Version 1 has just released with more functions.
