### ISSUE TITLE
Thoughts on being able to disable the entire dropdown button itself?

### ISSUE THREAD

**Issue by dvuke** [leovo2708/ng2-dropdown-treeview#12]
This is more of a feature request than an issue, so please handle accordingly.

I was just curious your thoughts on adding the ability to disable the entire dropdown button itself instead of just the individual tree items in it?

**Comment by leovo2708** [comment]
You can write a custom directive to disable any elements by selector. I included it in my demo: https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/
