### ISSUE TITLE
hi, customize checkedbox

### ISSUE THREAD

**Issue by puahyan** [leovo2708/ng2-dropdown-treeview#13]
hi, please check it in your mail,. thanks
need help on this. thanks!

**Comment by leovo2708** [comment]
You should set checked = false when create a TreeviewItem

const items: TreeviewItem[] = [];
const item = new TreeviewItem({ text: 'Item 1', value: 1, **checked: false** });
items.push(item);

**Comment by puahyan** [comment]
hi, it is still the same, i think i mistaken it is a bug.
if there is 4 levels, 
once the first child in fourth child is checked, the parent of this child also get checked

**Comment by puahyan** [comment]
like-wise, if forth level only has 2/3 child, and get all checked, while the 3rd ,2nd and first level dont have any child, 
like 1st>2nd>3rd>4th [ child1(checked), child 2(checked), child 3(checked)],
if this scenario, only 4th and child1 and child2 and child3 get checked, while 1st,2nd,3rd which has no child at all never get checked, it should checked as well.

**Comment by puahyan** [comment]
![treeview1](https://cloud.githubusercontent.com/assets/3817830/24441395/046f2862-148c-11e7-8245-cce5c6a7e923.jpg)

**Comment by puahyan** [comment]
![treeview2](https://cloud.githubusercontent.com/assets/3817830/24441512/707d2464-148c-11e7-9261-2f5092f4d1b8.jpg)
/resource id is 10,

**Comment by leovo2708** [comment]
Hi, if you don't set checked value, default is true. If any children has checked=false then parent must has checked=false. My component don't want to validate input data. So, please recheck your input. You can checkout my example 1 at here https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/

If this can't solve your problem, please upload your plunker code. I will help you. Thanks.

**Comment by puahyan** [comment]
hi i have sent to your mail

**Comment by puahyan** [comment]
i have sent to your mail

**Comment by leovo2708** [comment]
OK, I found problem. In my component, when an item is assigned with children, if all of children are checked=true, the parent will be updated to checked=true. So, you should change your code to make consistent. Thanks.

**Comment by puahyan** [comment]
which part i need to change ?

**Comment by puahyan** [comment]
the json data is fix, only the treeview array or any data structure coding
part need to change

**Comment by leovo2708** [comment]
=> Here is the place you set the item '/index.html' with checked=false
const accarrFirstItems =  new TreeviewItem({text:this.peritems[0].data[i].name,value:this.peritems[0].data[i].id,checked:false});

=> Here is the place you set children to it.
accarr[1][x].children = p[x];

=> I checked that all children of it have checked=true. So after this command, the item './index.html' will have checked=true.

**Comment by puahyan** [comment]
erm, can resend the entire fix code? then i can find the mistake, thanks

**Comment by leovo2708** [comment]
You should debug to understand what I said. I can't help you because your tree is very complex. A good solution is that you should create a full tree without checked state at root, only keep checked state of leaves. Finally, update checked of root from leaves.

**Comment by leovo2708** [comment]
const item = new TreeviewItem({
        text: 'Item1', value: 1, **checked: false**, children: [
            { text: 'Child1', value: 2, **checked: true** }
        ]
    });
console.log(item.checked) // =>output: true

**Comment by puahyan** [comment]
hi, this is a part of the module, thats why i create this.
each user have different roles and action, therefore each user have
different selectedperids as permission id,
 i only follow the way you do, but couldnt understand why my one cant make
it

**Comment by puahyan** [comment]
const accarrFirstItems =  new
TreeviewItem({text:this.peritems[0].data[i].name,value:this.peritems[0].data[i].id,checked:true});

**Comment by leovo2708** [comment]
You should understand that I am making consistent, a parent can't be un-checked while all of children are checked. So you should find a good point to assign children to avoid this problem.

**Comment by puahyan** [comment]
this is my updated code, it still same

**Comment by puahyan** [comment]
hi,  i really couldnt find solution. therefore i need your help.

**Comment by leovo2708** [comment]
Haha, as I said, my component only validate data from root to leaf, not validate from leaf to root. It's your job. If a leaf is un-checked -> I don't validate to make root is un-checked.

**Comment by leovo2708** [comment]
After you create you tree, you recheck all items. If leaf is un-checked =>set root is un-checked

**Comment by puahyan** [comment]
after i create a list tree, how can i recheck all item again?
1st, list all tree, 2nd check all the selected item.
i can do the first, but how to trigger the 2nd action?

**Comment by leovo2708** [comment]
I think it's not hard but a quite complex. I am busy, but will try to write a helper into my component to correct the tree like in your case.

**Comment by puahyan** [comment]
ok thanks, it look complex only,
the id is unique id, while pid is parent id.
while many id with different pid in lower level each parent, it will create
more sub level until infinity

**Comment by leovo2708** [comment]
Sorry, this is my mistake. I has just updated my component. Thanks.

**Comment by puahyan** [comment]
oh its ok, so i need to update the npm, package version

**Comment by puahyan** [comment]
hi, it is still the same, but if re-trigger the checked item again, then no problem
but how to do it..

**Comment by leovo2708** [comment]
Ok, my component has just updated. Please update it and then, in your code, calling this function:
```
totalpermissionitems[0].correctChecked();
return totalpermissionitems;
```

Please leave comment to give the result. Thanks.

**Comment by puahyan** [comment]
hi , just now i tested with multi levels tree , all working fine , each treeviewitem need to implement correct-checked after created the final tree .
thanks you so much, finally this had solved my problem.
