### ISSUE TITLE
Ability to show selected items in the order of selection rather than in the order they are displayed in the original list

### ISSUE THREAD

**Issue by Synster** [leovo2708/ng2-dropdown-treeview#14]
Hi,

Is there a way to get the selected items in the order they get selected rather than in the order they are currently displayed in the original list.

Like in the example 4 in the demo, we get selected items in the order they are originally displayed. Can I get selected items in the order I select.

Regards

**Comment by leovo2708** [comment]
I has just include built-in OrderDownlineTreeviewEventParser, you can use to get checked items in order they are checked. Read example 4 to understand how to use. Thanks.

**Comment by Synster** [comment]
Thanks Keep up the good work :)
