### ISSUE TITLE
Issue with (selectedChange) , selected change emits the items in the same way as they appear in the column tree

### ISSUE THREAD

**Issue by akvermaBLK** [leovo2708/ng2-dropdown-treeview#15]
(selectedChange) emits items in the same way they appear in the column tree.
Items should be emitted in the order they are checked.

**Comment by leovo2708** [comment]
I has just include built-in OrderDownlineTreeviewEventParser, you can use to get checked items in order they are checked. Read example 4 to understand how to use. Thanks.
