### ISSUE TITLE
toggle get checked , and unchecked items

### ISSUE THREAD

**Issue by puahyan** [leovo2708/ng2-dropdown-treeview#16]
hi, is there any way to create a function, a  button that clicked, 
a. display all checked item together with parents, like filter function
b. display all unchecked item together with parents, like filter function

**Comment by leovo2708** [comment]
You can do that. I have an example about DownlineTreeviewEventParser : https://github.com/leovo2708/ng2-dropdown-treeview/blob/master/src/treeview-event-parser.ts

You can follow it and do it yourself.

You can check example 4 here: https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/
