### ISSUE TITLE
Need help to get the tree from WebAPI

### ISSUE THREAD

**Issue by NitinTiwari1010** [leovo2708/ng2-dropdown-treeview#18]
Hi I need a help.. I need to get the tree values from WebAPI which is written in C#, do i need to create same class structure in C# for the below class so that i can bind the tree from my webAPI given tree.

export interface TreeItem {
    text: string;
    value: any;
    disabled?: boolean;
    checked?: boolean;
    collapsed?: boolean;
    children?: TreeItem[];
}
export declare class TreeviewItem {
    private internalDisabled;
    private internalChecked;
    private internalCollapsed;
    private internalChildren;
    text: string;
    value: any;
    constructor(item: TreeItem, autoCorrectChecked?: boolean);
    checked: boolean;
    setCheckedRecursive(value: boolean): void;
    disabled: boolean;
    collapsed: boolean;
    setCollapsedRecursive(value: boolean): void;
    children: TreeviewItem[];
    getCheckedItems(): TreeviewItem[];
    correctChecked(): void;
    private getCorrectChecked();
}

I tried to do that and created a C# class like below and able to generate a tree.. we cannot used "checked" property name in C#  so i changed to "ischecked" and i feel the issue is in getCheckedItems() method.  Please help..

  public class TreeItem
    {
        public string text { get; set; }
        public string value { get; set; }
        public bool? disabled { get; set; }
        public bool? ischecked { get; set; }
        public bool? collapsed { get; set; }
        public TreeItem[] children { get; set; }

    }
public class TreeviewItem
    {
        public string text { get; set; }
        public string value { get; set; }

        public bool disabled { get; set; }
        public bool ischecked { get; set; }
        public bool collapsed { get; set; }

        public TreeviewItem()
        { }

        public TreeviewItem(TreeItem item, bool? autoCorrectChecked)
        {
            text = item.text;
            value = item.value;
        }
        //  public TreeviewItem[] children { get; set; }        
        public List<TreeviewItem> children { get; set; }
        public void setCheckedRecursive(bool value) { }
        public void setCollapsedRecursive(bool value) { }
        public List<TreeviewItem> getCheckedItems() {

          List<TreeviewItem> objcheckedList = new List<TreeviewItem>();
            if (this.ischecked)
                objcheckedList.Add(this);
            return objcheckedList;
        }
        public void correctChecked() { }
        public void getCorrectChecked() { }

    }

Below method, i used to generate a tree..

 public TreeviewItemOutput GetTreeViewFocusSKU()
        {
            TreeviewItemOutput result = new TreeviewItemOutput();

            List<TreeviewItem> allAccountsTreeView = null;
            List<ChainHier> allChainHier = new List<ChainHier>();
            try
            {
                this.CreateSession();
                SqlParameter[] pars = { };

                SDMReader reader = this.ExecuteReader("FocusSKU.pGetChainHier", pars);
                if (reader != null)
                {
                    allChainHier = reader.GetResults<ChainHier>().ToList();
                }

                allAccountsTreeView = new List<TreeviewItem>();

                List<TreeviewItem> localchainTree = new List<TreeviewItem>();
                List<TreeviewItem> regionalChainTree = new List<TreeviewItem>();
               // List<TreeviewItem> nationalChainTree = new List<TreeviewItem>();

                var nationalAccounts = allChainHier.Select(i => new { i.NationalChainID, i.NationalChainName, i.SAPNationalChainID }).DistinctBy(i => i.NationalChainID).ToList();

               // nationalChainTree.AddRange(nationalAccounts.Select(i => new TreeviewItem() { text = i.NationalChainName, value = "National" + TREE_VIEW_SEPERATOR + i.NationalChainID + TREE_VIEW_SEPERATOR + i.SAPNationalChainID + TREE_VIEW_SEPERATOR + i.NationalChainName }));
               
                //Get all the regional accounts
                var regionalAccounts = (from allAccount in allChainHier
                                        join nationalaccount in nationalAccounts
                                        on allAccount.NationalChainID equals nationalaccount.NationalChainID
                                        select new { allAccount.RegionalChainID, allAccount.RegionalChainName, allAccount.SAPRegionalChainID, allAccount.NationalChainID }).DistinctBy(i => i.RegionalChainID).ToList();

                var localAccounts = (from allAccount in allChainHier
                                     join regionalaccount in regionalAccounts
                                     on allAccount.RegionalChainID equals regionalaccount.RegionalChainID
                                     select new { allAccount.LocalChainID, allAccount.LocalChainName, allAccount.SAPLocalChainID, allAccount.RegionalChainID, allAccount.NationalChainID }).DistinctBy(i => i.LocalChainID).ToList();

                localchainTree.AddRange(localAccounts.Select(i => new TreeviewItem() { text = i.LocalChainName, value = "Local" + TREE_VIEW_SEPERATOR + i.LocalChainID + TREE_VIEW_SEPERATOR + i.SAPLocalChainID + TREE_VIEW_SEPERATOR + i.LocalChainName }));

                regionalChainTree.AddRange(regionalAccounts.Select(i => new TreeviewItem() { text = i.RegionalChainName, value = "Regional" + TREE_VIEW_SEPERATOR + i.RegionalChainID + TREE_VIEW_SEPERATOR + i.SAPRegionalChainID + TREE_VIEW_SEPERATOR + i.RegionalChainName, children= localchainTree }));

                allAccountsTreeView.AddRange(nationalAccounts.Select(i => new TreeviewItem() { text = i.NationalChainName, value = "National" + TREE_VIEW_SEPERATOR + i.NationalChainID + TREE_VIEW_SEPERATOR + i.SAPNationalChainID + TREE_VIEW_SEPERATOR + i.NationalChainName, children = regionalChainTree }));

                result.ChainTreeView = allAccountsTreeView;
                return result;
            }
          

            catch (Exception e) { throw (e); }
            finally { this.CloseSession(); }
        }

I am getting the following issue, please help:

**error_handler.js:56 ORIGINAL EXCEPTION: this.items[i].getCheckedItems is not a function**

**Comment by leovo2708** [comment]
I think you should read my demo with example code: https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/
In backend, you return a list of TreeItem.
In frontend, you create a list of TreeviewItem from list of TreeItem.
`const treeviewItems = treeItems.map(item => new TreeviewItem(item));`

And finally, binding treeviewItems into my component. It's very easy to apply.

**Comment by NitinTiwari1010** [comment]
Thanks a lot for your help, working on this and update you..Thanks again.

**Comment by NitinTiwari1010** [comment]
Hi,
Please suggest:

I did the same as you mentioned but getting below error:
**error_handler.js:54 EXCEPTION: Children must be not an empty array**

Note: My tree structure has three level and at last level children is empty.. please help, below is the JSON i am getting from my webapi:

{
ChainTreeView: [
{
ID: 137,
ParentID: 0,
text: "24 Hour Fitness",
value: "National^137^1013788^24 Hour Fitness",
disabled: null,
checked: null,
collapsed: null,
children: [
{
ID: 511,
ParentID: 137,
text: "24 Hour Fitness",
value: "Regional^511^1013789^24 Hour Fitness",
disabled: null,
checked: null,
collapsed: null,
children: [
{
ID: 3155,
ParentID: 511,
text: "Cs 24 Hour Fitness",
value: "Local^3155^1013798^Cs 24 Hour Fitness",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
}
]
}
]
},
{
ID: 55,
ParentID: 0,
text: "7 Eleven",
value: "National^55^1001451^7 Eleven",
disabled: null,
checked: null,
collapsed: null,
children: [
{
ID: 176,
ParentID: 55,
text: "7 Eleven Inc",
value: "Regional^176^1001452^7 Eleven Inc",
disabled: null,
checked: null,
collapsed: null,
children: [
{
ID: 10,
ParentID: 176,
text: "Clsd 7 Eleven Southland",
value: "Local^10^1000115^Clsd 7 Eleven Southland",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 90,
ParentID: 176,
text: "7 Eleven Appalachian",
value: "Local^90^1000241^7 Eleven Appalachian",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 324,
ParentID: 176,
text: "7 Eleven Liberty",
value: "Local^324^1000535^7 Eleven Liberty",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 2452,
ParentID: 176,
text: "Clsd 7 Eleven Rocky Mtn",
value: "Local^2452^1003394^Clsd 7 Eleven Rocky Mtn",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 3067,
ParentID: 176,
text: "7 Eleven Acquisitions",
value: "Local^3067^1013196^7 Eleven Acquisitions",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 3068,
ParentID: 176,
text: "7 Eleven Greater La",
value: "Local^3068^1013197^7 Eleven Greater La",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 3069,
ParentID: 176,
text: "7 Eleven Heartland",
value: "Local^3069^1013198^7 Eleven Heartland",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 3070,
ParentID: 176,
text: "7 Eleven Lone Star",
value: "Local^3070^1013199^7 Eleven Lone Star",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
},
{
ID: 3071,
ParentID: 176,
text: "7 Eleven N Atl",
value: "Local^3071^1013200^7 Eleven N Atl",
disabled: null,
checked: null,
collapsed: null,
children: [ ]
}
]
}
]
}
],
ReturnStatus: 1,
Message: null,
CorrelationID: "70e980a5-f648-4c53-90a7-0dd23f3af526",
StackTrace: null
}
