### ISSUE TITLE
Not multi select

### ISSUE THREAD

**Issue by Rudimo** [leovo2708/ng2-dropdown-treeview#2]
Whether it is possible to select only one item?

**Comment by leovo2708** [comment]
Yes, first you uncheck 'All' checkbox to uncheck all of items and then check only one item which you want.
This is my demo: [https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/](https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/)
