### ISSUE TITLE
TreeViewItem Template

### ISSUE THREAD

**Issue by nm-a** [leovo2708/ng2-dropdown-treeview#21]
Hi,
Thank you for the decent treeview, I see this is very useful in most of the scenarios. Can we add row template in TreeViewItem. For example if we need to display more than one column in a row & add buttons (edit / delete), the template might be helpful.

Can you suggest, is there any better alternative to address these kind of scenarios.

thank you
-nm

**Comment by leovo2708** [comment]
Good idea, I will update it ASAP.

**Comment by nm-a** [comment]
Thank you :+1:

**Comment by leovo2708** [comment]
It's now supported. Check example 1 & 4:
https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/

**Comment by nm-a** [comment]
Hi, Thank you for quick response. I see still component is expecting TreeViewItem; couldn't get how can we bring customization. For example if I want to pass my own object as list to [items] & display in the custom columns / format.

Can you please let me know if I am missing something here..


thank you
-nm

**Comment by nm-a** [comment]
Thank you, it is very helpful.

**Comment by leovo2708** [comment]
I have updated example 4: https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/
It has button Delete.

**Comment by nm-a** [comment]
Excellent, people can use this as TreeList as well

http://demos.telerik.com/kendo-ui/treelist/remote-data-binding

thank you
-nm
