### ISSUE TITLE
MouseEvent is not defined. 

### ISSUE THREAD

**Issue by chris601** [leovo2708/ng2-dropdown-treeview#22]
DropdownTreeviewModule - DropdownTreeviewModule.forRoot()

with visual studio angular2  adding your library causes this issue 

Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: MouseEvent is not defined.

**Comment by leovo2708** [comment]
You must import "dom" lib in tsconfig.json.

**Comment by chris601** [comment]
This has defiantly been included.  This is my tsconfig.json file

{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "lib": [ "es6", "dom" ],
    "types": [ "node" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}
