### ISSUE TITLE
MouseEvent is not defined

### ISSUE THREAD

**Issue by chris601** [leovo2708/ng2-dropdown-treeview#23]
DropdownTreeviewModule - DropdownTreeviewModule.forRoot()
with visual studio angular2 adding your library causes this issue
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: MouseEvent is not defined.

lib Dom is include within my tsconfig tried reopening issue but no option to do so.

{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "lib": [ "es5", "dom" ],
    "types": [ "node" ],
    "Lib": [ "2016", "DOM" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}

**Comment by chris601** [comment]
This may help 

https://github.com/valor-software/ngx-bootstrap/commit/d20ccf1
https://github.com/valor-software/ng2-select/issues/258

**Comment by leovo2708** [comment]
I think you should try to build your angular project by NodeJS command line, I make sure it will be successful. If it is failure, please write the error message from NodeJS here. Don't believe in result from Visual Studio output, because it is from Typescript extension, sometimes it doesn't work exactly.

**Comment by leovo2708** [comment]
Thank you for your reference but I don't like hacking. It's a bad solution. I really applied my component in some projects with no problem. Some people are also using my component, and don't have any issue. You can also refer the demo in my github source.

And finally, I would like to say again: you should write error from NodeJS command line, not from Visual Studio error output. Thanks.

**Comment by nm-a** [comment]
hi @chris601 , I am using this components from Visual Studio. I don't see any issue; let me share my tsconfi file.

**Comment by nm-a** [comment]
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "target": "es5",
    "module": "es2015",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "assets",
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by chris601** [comment]
Still really at a loss what to do, I'm sure that it is not my ts config.   This is more to do with this 
valor-software/ng2-select#258.  As for visual studio,  That is what I'm currently working in.  It sets up a template for your project.  probably could set this up to work with node in the cmd but would mean a lot of changes to my code base  and how my project is.   hack is just bad terminology for fix to the library  which generally you shouldn't be changing.

Any help for a solution would be appreciated.

**Comment by leovo2708** [comment]
Visual Studio is getting many problems with Typescript. So I stopped using it & began using Visual Studio Code. Only hope Typescript in Visual Studio will be stable in next version. So, I will close this issue because it is related to Visual Studio, not my component. Thanks.

**Comment by chris601** [comment]
The only way I've found to get around my issue is to turn prerendering off in the index file of the visual studio, I don't think this is ideal.  This has nothing to do with the typescript setup.  this is due to the mouse event not being define at the prerender stage and is a common issue in angular libraries.  it is also to do with 
import { UniversalModule } from 'angular2-universal';

this is outlined in 
valor-software/ng2-select#258

If you get a chance maybe you could fix your library.  Thank you for the time you have spent on this

"\<app>Loading...\</app>"
"@*\<app asp-prerender-module="ClientApp/dist/main-server">Loading...\</app>*@"

**Comment by leovo2708** [comment]
MouseEvent is defined in dom library which you included:
https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L8085

However, I don't understand why Visual Studio got mistake here, maybe Typescript extenstion is too old or any other reasons.

Some components and libraries (ex: angular) also ever apply your suggested solution, because Typescript at that time didn't define MouseEvent. But after it defined, these components removed redundant code.

**Comment by chris601** [comment]
Mouse Event is not defined pre-render in which visual studio pre renders.  Therefor you get the error mouse event is not defined unless you remove the pretender statement from the index on visual studio.  My link tells you all of this in a round about way.  This doesn't just effect mouse event.

**Comment by leovo2708** [comment]
An new component for Angular4 is being built. Hope it will work better when using Angular CLI. The current version for Angular2 is discontinued. Thanks.

**Comment by leovo2708** [comment]
Try to use my new component for Angular 4:
https://www.npmjs.com/package/ngx-treeview

**Comment by priyankakolee** [comment]
On change of Parent checkbox, I don't want children to be selected/deselected. Need to override onCheckedChange(), Can you guide me how to?
