### ISSUE TITLE
 <ng-template> instead <template>

### ISSUE THREAD

**Issue by mizi-lin** [leovo2708/ng2-dropdown-treeview#24]
> Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
< div class="treeview-item">
    [WARNING ->]<template [ngTemplateOutlet]="template"
        [ngOutletContext]="{item: item, toggleCollapseExpand:"): ng:///DropdownTreeviewModule/TreeviewItemComponent.html@2:4

**Comment by leovo2708** [comment]
I will fix it when upgrade to Angular 4.

**Comment by leovo2708** [comment]
I upgraded my component to Angular 4 with new name: [ngx-treeview](https://www.npmjs.com/package/ngx-treeview)
