### ISSUE TITLE
Cant add children to tempTreeView

### ISSUE THREAD

**Issue by chris601** [leovo2708/ng2-dropdown-treeview#26]
Hi 

I cant add children to TreeviewItem if children has not previously been added for the TreeviewItem.  

ie.

const vegetableCategory = new TreeviewItem({
            text: 'Vegetable', value: 2
        });
vegetableCategory.children.push(new TreeviewItem({ text: 'Mushroom', value: 23, checked: false })); 

Is there a fix for this.

**Comment by leovo2708** [comment]
You must use this way:
vegetableCategory.children = [new TreeviewItem({ text: 'Mushroom', value: 23, checked: false })];

**Comment by chris601** [comment]
Thank you
