### ISSUE TITLE
Adding Multiple checkboxes.

### ISSUE THREAD

**Issue by chris601** [leovo2708/ng2-dropdown-treeview#28]
Hi

Is there anyway of adding more than one checkbox to a treeview item.  i.e.  I would like to use it within an admin page allowing read and/or write access to a selected item.  I can get round this by using a dropdownlist but think it would be a really nice feature.

Thank you for your time.

**Comment by leovo2708** [comment]
Yes, it's able if you write a custom template, check my example 4: https://embed.plnkr.co/1kcbUvNze8HAJ0tN0wsX/

**Comment by chris601** [comment]
Is it possible for me to amend the TreeviewItem so that is can handle multiple checked items ?
