### ISSUE TITLE
Performance Issue on treeview

### ISSUE THREAD

**Issue by NitinTiwari1010** [leovo2708/ng2-dropdown-treeview#29]
Hi, 
As per our requirement, we have added 3 treeview control on one component (Angular2 ) which has around 700 nodes in 3 level hierarchy in each tree control, i am facing the performance issue, Please let me know how to improve the performance.  we checked the following:

1. WebAPI getting tree data in ms (fast) but binding to tree control giving performance issue.
2. Performance is ok on chrome but bad on IE 11. We need to fix on IE 11.
3. We are showing tree in collapsed mode as well to improve performance but even it is not good.
4. As we are fetching data from WebAPI so doing below two step before bind data in tree control:

Step 1: - this.deleteEmptyChildrenNode(container.ChainTreeView);  /// Delete the Empty tree children node
Step 2: this.ChainTreeData = container.ChainTreeView.map(item => new TreeviewItem(item));  // Map to TreeviewItem class.

 <leo-treeview [items]="ChainTreeData" [config]="ChainConfig" [template]="tpl">
                        </leo-treeview>

**Function details** 
  deleteEmptyChildrenNode(array) {
    for (var i = 0; i < array.length; ++i) {
      var obj = array[i];
      if (obj.children) {
        if (obj.children.length === 0)
          delete obj.children;
        else
          this.deleteEmptyChildrenNode(obj.children);
      }
    }
  }

Please suggest.

**Comment by leovo2708** [comment]
Please use my new component [ngx-treeview](https://www.npmjs.com/package/ngx-treeview) and post your issue on it.
