### ISSUE TITLE
i can not bootstrap follow your steps.

### ISSUE THREAD

**Issue by badboy-huaqiao** [leovo2708/ng2-dropdown-treeview#3]
i can not apply TreeMoudle in my module follow your steps.

with web console error :Uncaught SyntaxError: Unexpected reserved word

**Comment by leovo2708** [comment]
I applied my components in some projects and it's working smoothly without any problem. From stackoverflow: http://stackoverflow.com/questions/36722016/syntaxerror-unexpected-reserved-word, I guess this error is from webpack, please recheck your nodejs packages or upload your source on GitHub and I will help you to investigate. Thanks.

**Comment by badboy-huaqiao** [comment]
i find the problem ,your webpack version is 2.x ,my is 1.x ,so my project can not load your module.
beacause your module with "export * from .." in your index.ts, webpack 1.x can not resolve this statement, but i can not know how fix it, please help me ,thanks.

**Comment by leovo2708** [comment]
Please give me your full error log. I think webpack is not reason in this case.

**Comment by badboy-huaqiao** [comment]
this is  the browser console output where is in app.bundle.js. thanks.

/***/ 831:
/***/ function(module, exports) {

	eval("export * from './src/dropdown-treeview.module';\r\nexport * from './src/dropdown-treeview.component';\r\nexport * from './src/treeview.component';\r\nexport * from './src/treeview.pipe';\r\n//# sourceMappingURL=index.js.map//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiODMxLmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vfi9uZzItZHJvcGRvd24tdHJlZXZpZXcvaW5kZXguanM/ZTQyYyJdLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgKiBmcm9tICcuL3NyYy9kcm9wZG93bi10cmVldmlldy5tb2R1bGUnO1xyXG5leHBvcnQgKiBmcm9tICcuL3NyYy9kcm9wZG93bi10cmVldmlldy5jb21wb25lbnQnO1xyXG5leHBvcnQgKiBmcm9tICcuL3NyYy90cmVldmlldy5jb21wb25lbnQnO1xyXG5leHBvcnQgKiBmcm9tICcuL3NyYy90cmVldmlldy5waXBlJztcclxuLy8jIHNvdXJjZU1hcHBpbmdVUkw9aW5kZXguanMubWFwXG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9+L25nMi1kcm9wZG93bi10cmVldmlldy9pbmRleC5qc1xuLy8gbW9kdWxlIGlkID0gODMxXG4vLyBtb2R1bGUgY2h1bmtzID0gMCJdLCJtYXBwaW5ncyI6IkFBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQSIsInNvdXJjZVJvb3QiOiIifQ==");

/***/ }

**Comment by leovo2708** [comment]
I think you miss core-js module, must include it in polyfills. Could you tell me which angular 2 template you used to startup your project, or upload your project on GitHub. I will help you easier.
