### ISSUE TITLE
How to change placeholder?

### ISSUE THREAD

**Issue by samuelcastro** [leovo2708/ng2-dropdown-treeview#30]
I didn't find any documentation about how to change placeholder? Is there a way to?

**Comment by ivarkrs** [comment]
How to change filter input box place holder? See below
 TreeviewI18nDefault.prototype.filterPlaceholder = function () {
            return 'Place holder';
        };

**Comment by leovo2708** [comment]
Please upgrade to ngx-treeview. You can build a custom template to help you to bind [placeholder]
