### ISSUE TITLE
How to get parentId When Parent is Selected?

### ISSUE THREAD

**Issue by lakshmipunati** [leovo2708/ng2-dropdown-treeview#4]
When Iam Selecting parents its showing all the child Ids,But how can i get 'parentId' from the Selected list Including with children?? Also,Is this possible to View children inside children?

<img width="960" alt="treedropdown" src="https://cloud.githubusercontent.com/assets/24697650/22851339/b83b3e60-f044-11e6-85d1-659cd204173c.png">

**Comment by leovo2708** [comment]
When changing checked state of an item, the text on dropdown button also changes and it is the total of checked items which don't have parent. So, param of change event doesn't include parentId. However, you can get parentId if want. Use @ViewChild to access to component instance and use property filterItems to get tree items with both parentId & childId.
