### ISSUE TITLE
Tree-view without drop-down but WITH filter input-field

### ISSUE THREAD

**Issue by Moalpima** [leovo2708/ng2-dropdown-treeview#5]
Hi,

first: good job. This component is very cool. But how can I show the filter input-field when I want to use your "Example 4" (Tree-view without drop-down)?

Best regards

Dirk

**Comment by leovo2708** [comment]
Thank for your comment. My component is coming with more features. And as I know, Angular will have version 4 in near future. I will need to change to new component name: angular-treeview, and at this time, you will see this feature which you want.

This issue will be opened until a new component name is released.

**Comment by Moalpima** [comment]
Cool. Thank you for your answer. I am very curious about the new features. When do you expect to release the update?

**Comment by leovo2708** [comment]
Version 1 has just released with more functions.
