### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by yogesh2singh** [leovo2708/ng2-dropdown-treeview#6]
Hi,

I am planning to use this library but no license is attached. Can you please add a license.

**Comment by leovo2708** [comment]
License MIT is really attached here: https://www.npmjs.com/package/ng2-dropdown-treeview

**Comment by JarleStrand** [comment]
Hi, It would be great to also have a license file here on github. Also, it's not very clearly stated that you distribute this under MIT just because you have a link to the MIT license on the pages linked above. 

I think a license file on github would help spread the use of this great package :)

**Comment by leovo2708** [comment]
License is attached. Version 1 has just released with more functions.
